# Generated by Django 2.2.6 on 2020-04-29 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AmazonReferralLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amazon_referral_url', models.CharField(help_text='Referral part of the link only (without https://www.amazon.com/', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='BookCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('headline', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('seo_title', models.CharField(blank=True, max_length=60, null=True)),
                ('seo_description', models.CharField(blank=True, max_length=165, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Book Category',
                'verbose_name_plural': 'Book Categories',
                'db_table': 'category',
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(blank=True, max_length=200, null=True)),
                ('rating_good_reads', models.CharField(blank=True, default='NA', max_length=10, null=True)),
                ('rating_amazon', models.CharField(blank=True, default='NA', max_length=10, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('url', models.URLField(help_text='Url to amazon.', max_length=250)),
                ('book_image', models.ImageField(blank=True, null=True, upload_to='book-covers/')),
                ('is_active_category', models.BooleanField(default=False, help_text='Is it displayed on category page?')),
                ('is_highlighted_category', models.BooleanField(default=False, help_text='Is it highlighted on main page?')),
                ('is_active_main', models.BooleanField(default=False, help_text='Is it displayed on main page?')),
                ('is_highlighted_main', models.BooleanField(default=False, help_text='Is it highlighted on main page?')),
                ('has_audiobook', models.BooleanField(blank=True, default=False, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('categories', models.ManyToManyField(blank=True, to='books.BookCategory')),
            ],
            options={
                'verbose_name': 'Book',
                'verbose_name_plural': 'Books',
                'db_table': 'book',
                'ordering': ('is_highlighted_category', 'title'),
            },
        ),
    ]
