# Generated by Django 2.2.6 on 2020-05-01 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='rating_amazon',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='rating_goodreads',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
