# Generated by Django 2.2.6 on 2020-04-30 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_auto_20200430_0836'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='rating_good_reads',
            new_name='rating_goodreads',
        ),
        migrations.AddField(
            model_name='book',
            name='url_goodreads',
            field=models.URLField(blank=True, help_text='Url to good reads.', max_length=250, null=True),
        ),
    ]
