# Generated by Django 2.0.6 on 2018-06-26 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20180626_1404'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='feed_url',
        ),
    ]
