# Generated by Django 2.0.6 on 2018-06-27 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_post_feed_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='parse_content',
            field=models.BooleanField(default=True),
        ),
    ]
