# Generated by Django 2.0.6 on 2018-06-27 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20180627_1130'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='other_tags',
            field=models.ManyToManyField(blank=True, to='core.OtherTag'),
        ),
    ]
