# Generated by Django 2.0.6 on 2018-06-28 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_post_other_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='url_feed',
            field=models.URLField(default='#', max_length=250),
            preserve_default=False,
        ),
    ]
