# Generated by Django 2.0.6 on 2018-07-03 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_post_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feed',
            name='parse_content',
        ),
        migrations.AddField(
            model_name='othertag',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tag',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='source_url',
            field=models.URLField(help_text='URL of the original article.', max_length=250),
        ),
    ]
